### ISSUE TITLE
新语言:Pytlnon

### ISSUE THREAD

**Issue by cheny0y0** [TZG-official/Jvav#102]
repository打算建在@cheny0y0 /pytlnon里,如果有重大问题,我会创建一个organization然后transfer进去

**Comment by cheny0y0** [comment]
#100

**Comment by AMIRIOX** [comment]
草, v0.0可还行
[语义化版本](https://semver.org/lang/zh-CN/)

**Comment by TheZihanGu** [comment]
都这么喜欢整活吗...

**Comment by cheny0y0** [comment]
> 草, v0.0可还行
> [语义化版本](https://semver.org/lang/zh-CN/)

哈哈哈，还真有，并且不止我

**Comment by cheny0y0** [comment]
> > 草, v0.0可还行
> > [语义化版本](https://semver.org/lang/zh-CN/)
> 
> 哈哈哈，还真有，并且不止我

国外大多数release版本从v0.0beta开始，然后是v0.0或v0.1
