### ISSUE TITLE
网站报错：523 Origin is unreachable

### ISSUE THREAD

**Issue by Destroy-God** [TZG-official/Jvav#103]
Error 523 Ray ID: 5e00a729e941e7f5 • 2020-10-10 13:22:55 UTC
If you're the owner of this website:
Check your DNS Settings. A 523 error means that Cloudflare could not reach your host web server. The most common cause is that your DNS settings are incorrect. Please contact your hosting provider to confirm your origin IP and then make sure the correct IP is listed for your A record in your Cloudflare DNS Settings page. Additional troubleshooting information here.

**Comment by TheZihanGu** [comment]
确实。可能是源站服务器炸掉了，将在近期进行修复。

**Comment by cheny0y0** [comment]
> 确实。可能是源站服务器炸掉了，将在近期进行修复。

修好了吗？[:smile:]

**Comment by TheZihanGu** [comment]
> > 确实。可能是源站服务器炸掉了，将在近期进行修复。
> 
> 修好了吗？[😄]

懒。

**Comment by cheny0y0** [comment]
> > > 确实。可能是源站服务器炸掉了，将在近期进行修复。
> > 
> > 修好了吗？😄
> 
> 懒。

不搞Jvav了吗？:laugh:

**Comment by TheZihanGu** [comment]
目前 Jvav 官网已经恢复正常服务。
同时，你也可以查看 [TZG Status](https://status.tzg6.com)来检查其他服务的工作情况。

**Comment by g-aghayev** [comment]
jvav.top 怎么又 522 了?

作为替代，请访问 <https://jvav.cf> 

使用 GItLab Page 发布
