### ISSUE TITLE
无法上传新的页面及其资源

### ISSUE THREAD

**Issue by luckystar5408** [TZG-official/Jvav#107]
嗨！
我遇到了问题：

- 当我使用github上传新页面以及它的资源时，GitHub提示我无法上传文件

- 当我用git上传时，依旧无法上传，提示权限不足

请帮我解决，谢谢！

**Comment by TheZihanGu** [comment]
Please try to fork this repository, and then edit your fork repository through Git.
If you want to merge into this repository, try to create a pull request.

View GitHub Docs: [Editing files in another user's repository](https://docs.github.com/en/free-pro-team@latest/github/managing-files-in-a-repository/editing-files-in-another-users-repository)

**Comment by luckystar5408** [comment]
Thanks
