### ISSUE TITLE
We need English!（狗头

### ISSUE THREAD

**Issue by leostudiooo** [TZG-official/Jvav#110]
所以我想开始着手制作英文的页面翻译了，有大佬加入吗（

   贯彻Jvav精神，把Jvav推广到全世界（狗头）;

）

**Comment by xiaopangju** [comment]
我觉得有个问题需要讨论:英语的风格是应该完全地道，还是让中国人看了笑笑就可以（比如用完全中文的语法)

**Comment by TheZihanGu** [comment]
建议适当添加美式梗，如果真有人来看的话可能更容易理解些...

**Comment by xiaopangju** [comment]
> 建议适当添加美式梗，如果真有人来看的话可能更容易理解些...

或许可以加点英语特供，比如把rick（唱_never gonna give you up_的那个）p成张浩洋

**Comment by TheZihanGu** [comment]
> > 建议适当添加美式梗，如果真有人来看的话可能更容易理解些...
> 
> 或许可以加点英语特供，比如把rick（唱_never gonna give you up_的那个）p成张浩洋
那可太草了🤔

**Comment by xiaopangju** [comment]
> > > 建议适当添加美式梗，如果真有人来看的话可能更容易理解些...
> > 
> > 或许可以加点英语特供，比如把rick（唱_never gonna give you up_的那个）p成张浩洋
> 
> 那可太草了🤔

有条件的话可以做一下

**Comment by leostudiooo** [comment]
we're possibly rickrolled x
we're possibly Hoangrolled √


-------- Original message --------

**Comment by cheny0y0** [comment]
> 我觉得有个问题需要讨论:英语的风格是应该完全地道，还是让中国人看了笑笑就可以（比如用完全中文的语法)

比如“张浩杨”要翻译成“Zhang Haoyang”还是“Haoyang Zhang”。。。

**Comment by xiaopangju** [comment]
为了避免这个问题，直接翻译成Dr. Zhang 吧

Yours faithfully,
xiaopangju
________________________________

**Comment by TheZihanGu** [comment]
所以这个有人在做吗🤔

**Comment by xiaopangju** [comment]
我还在一点一点翻译

Yours faithfully,
xiaopangju
________________________________
