### ISSUE TITLE
真4鸽人才

### ISSUE THREAD

**Issue by tinyvan** [TZG-official/Jvav#14]
前来围观
顺便问一下网站logo小孩头出处是哪里呀

**Comment by tinyvan** [comment]
奥,找到了,膜拜张养浩大佬
我到现在还只会写几个c开头的语言
想做个gui框架,却因为学习压力迟迟不开工
只能等考完试了

**Comment by hongshige** [comment]
绝了

**Comment by TheZihanGu** [comment]
那位小朋友自己的头像就是这个图。
顺便一提，他似乎并没有参与任何分支的Jvav开发...
