### ISSUE TITLE
The Jvav Compiler

### ISSUE THREAD

**Issue by MagicLu550** [TZG-official/Jvav#15]
You can download the jvav in https://github.com/MagicLu550/jvav

**Comment by TheZihanGu** [comment]
Sorry, the branch version made by @ 30266 is currently published on this website.
And please do not place ads here. We will make a page later to present all the branch versions for others to download.

**Comment by MagicLu550** [comment]
> Sorry, the branch version made by @ 30266 is currently published on this site.
> And please do not place ads here. We will make a page later to present all the branch versions for others to download.

Ok,thank you

**Comment by MagicLu550** [comment]
jvav is best (dog head
