### ISSUE TITLE
[建议]Readme中添加其在MC群宣传迷你的事迹

### ISSUE THREAD

**Issue by SuperEndermanSM** [TZG-official/Jvav#21]

**Comment by TheZihanGu** [comment]
目前我并不清楚张浩扬博士在MC群宣传迷你世界的具体事迹。
如果可以的话，请在这里进行Comment，我会进行修改。
当然你也可以直接编辑README.md，然后进行Pull Request.

**Comment by RimuruChan** [comment]
张浩扬博士太草

**Comment by Misaka12456** [comment]
张浩扬博士草

**Comment by TheZihanGu** [comment]
emm张浩扬博士有什么问题么...

**Comment by zhishixiang** [comment]
张浩扬博士草

**Comment by WangWenBin2017** [comment]
b站过来的，大半夜笑死我了，前来观摩jvav语言

**Comment by MicroSwing** [comment]
魔鬼

**Comment by kurisucat** [comment]
张浩扬博士巨草

**Comment by TTomDuan** [comment]
我去弄个**qython**的梗

**Comment by APJifengc** [comment]
张浩扬博士草

**Comment by ORANGE-233** [comment]
群里有人谈jvav，我还纳闷，然后找到这里，可太艹了，是我才学浅薄了

**Comment by ORANGE-233** [comment]
不过啥时候出个jvavscript，虽然两者关联及其微小。
C--啊pythan啊HPH啊HTNL啊SCC啊Myspl乱七八糟的，最好再出个Liunx，有了这些，然后进军移动领域：Anbread和l(L)OS。光有软件肯定是不行的，最好研究一下微处理器，名字我想好了，就叫“低堵-哓龙”好了，这是移动端，pc端可以叫嘤特尔(intal)-库刻。啥显卡啊内存的储存啊乱七八糟的。

**Comment by ORANGE-233** [comment]
不过啥时候出个jvavscript，虽然两者关联及其微小。
C--啊pythan啊HPH啊HTNL啊SCC啊Myspl乱七八糟的，最好再出个Liunx，有了这些，然后进军移动领域：Anbread和l(L)OS。光有软件肯定是不行的，最好研究一下微处理器，名字我想好了，就叫“低堵-哓龙”好了，这是移动端，pc端可以叫嘤特尔(intal)-库刻。啥显卡啊内存啊储存啊乱七八糟的先不着急

**Comment by TTomDuan** [comment]
嘿嘿这个想法很先进

**Comment by APJifengc** [comment]
> 
> 
> 不过啥时候出个jvavscript，虽然两者关联及其微小。
> C--啊pythan啊HPH啊HTNL啊SCC啊Myspl乱七八糟的，最好再出个Liunx，有了这些，然后进军移动领域：Anbread和l(L)OS。光有软件肯定是不行的，最好研究一下微处理器，名字我想好了，就叫“低堵-哓龙”好了，这是移动端，pc端可以叫嘤特尔(intal)-库刻。啥显卡啊内存啊储存啊乱七八糟的先不着急

哈哈兄弟 你想累死我么 我的翻新JVAV还没写完 甚至ALPHA都不到

**Comment by TheZihanGu** [comment]
> 不过啥时候出个jvavscript，虽然两者关联及其微小。
> C--啊pythan啊HPH啊HTNL啊SCC啊Myspl乱七八糟的，最好再出个Liunx，有了这些，然后进军移动领域：Anbread和l(L)OS。光有软件肯定是不行的，最好研究一下微处理器，名字我想好了，就叫“低堵-哓龙”好了，这是移动端，pc端可以叫嘤特尔(intal)-库刻。啥显卡啊内存啊储存啊乱七八糟的先不着急

你可以尝试去写一下...
不过在浏览器中被标为```text/jvavscript```应该还会根据 JavaScript 继续执行代码。
因此...我觉得将 JavaScript 混淆后当作 JvavScript 可能还不错（？

**Comment by ORANGE-233** [comment]
> > 不过啥时候出个jvavscript，虽然两者关联及其微小。
> > C--啊pythan啊HPH啊HTNL啊SCC啊Myspl乱七八糟的，最好再出个Liunx，有了这些，然后进军移动领域：Anbread和l(L)OS。光有软件肯定是不行的，最好研究一下微处理器，名字我想好了，就叫“低堵-哓龙”好了，这是移动端，pc端可以叫嘤特尔(intal)-库刻。啥显卡啊内存啊储存啊乱七八糟的先不着急
> 
> 你可以尝试去写一下...
> 不过在浏览器中被标为`text/jvavscript`应该还会根据 JavaScript 继续执行代码。
> 因此...我觉得将 JavaScript 混淆后当作 JvavScript 可能还不错（？

像jQuery这类打包成一个库我觉得也星

**Comment by APJifengc** [comment]
> 
> 
> > > 不过啥时候出个jvavscript，虽然两者关联及其微小。
> > > C--啊pythan啊HPH啊HTNL啊SCC啊Myspl乱七八糟的，最好再出个Liunx，有了这些，然后进军移动领域：Anbread和l(L)OS。光有软件肯定是不行的，最好研究一下微处理器，名字我想好了，就叫“低堵-哓龙”好了，这是移动端，pc端可以叫嘤特尔(intal)-库刻。啥显卡啊内存啊储存啊乱七八糟的先不着急
> > 
> > 
> > 你可以尝试去写一下...
> > 不过在浏览器中被标为`text/jvavscript`应该还会根据 JavaScript 继续执行代码。
> > 因此...我觉得将 JavaScript 混淆后当作 JvavScript 可能还不错（？
> 
> 像jQuery这类打包成一个库我觉得也星

哈哈哈 反正不要找我 我很很很很菜的

**Comment by ORANGE-233** [comment]
> > > > 不过啥时候出个jvavscript，虽然两者关联及其微小。
> > > > C--啊pythan啊HPH啊HTNL啊SCC啊Myspl乱七八糟的，最好再出个Liunx，有了这些，然后进军移动领域：Anbread和l(L)OS。光有软件肯定是不行的，最好研究一下微处理器，名字我想好了，就叫“低堵-哓龙”好了，这是移动端，pc端可以叫嘤特尔(intal)-库刻。啥显卡啊内存啊储存啊乱七八糟的先不着急
> > > 
> > > 
> > > 你可以尝试去写一下...
> > > 不过在浏览器中被标为`text/jvavscript`应该还会根据 JavaScript 继续执行代码。
> > > 因此...我觉得将 JavaScript 混淆后当作 JvavScript 可能还不错（？
> > 
> > 
> > 像jQuery这类打包成一个库我觉得也星
> 
> 哈哈哈 反正不要找我 我很很很很菜的

这梗过不去了hhhhhhhh

**Comment by TTomDuan** [comment]
> > > > > 不过啥时候出个jvavscript，虽然两者关联及其微小。
> > > > > C--啊pythan啊HPH啊HTNL啊SCC啊Myspl乱七八糟的，最好再出个Liunx，有了这些，然后进军移动领域：Anbread和l(L)OS。光有软件肯定是不行的，最好研究一下微处理器，名字我想好了，就叫“低堵-哓龙”好了，这是移动端，pc端可以叫嘤特尔(intal)-库刻。啥显卡啊内存啊储存啊乱七八糟的先不着急
> > > > 
> > > > 
> > > > 你可以尝试去写一下...
> > > > 不过在浏览器中被标为`text/jvavscript`应该还会根据 JavaScript 继续执行代码。
> > > > 因此...我觉得将 JavaScript 混淆后当作 JvavScript 可能还不错（？
> > > 
> > > 
> > > 像jQuery这类打包成一个库我觉得也星
> > 
> > 
> > 哈哈哈 反正不要找我 我很很很很菜的
> 
> 这梗过不去了hhhhhhhh

hhhhhhhhhhhhhhhhh

**Comment by ORANGE-233** [comment]
> > > > > > 不过啥时候出个jvavscript，虽然两者关联及其微小。
> > > > > > C--啊pythan啊HPH啊HTNL啊SCC啊Myspl乱七八糟的，最好再出个Liunx，有了这些，然后进军移动领域：Anbread和l(L)OS。光有软件肯定是不行的，最好研究一下微处理器，名字我想好了，就叫“低堵-哓龙”好了，这是移动端，pc端可以叫嘤特尔(intal)-库刻。啥显卡啊内存啊储存啊乱七八糟的先不着急
> > > > > 
> > > > > 
> > > > > 你可以尝试去写一下...
> > > > > 不过在浏览器中被标为`text/jvavscript`应该还会根据 JavaScript 继续执行代码。
> > > > > 因此...我觉得将 JavaScript 混淆后当作 JvavScript 可能还不错（？
> > > > 
> > > > 
> > > > 像jQuery这类打包成一个库我觉得也星
> > > 
> > > 
> > > 哈哈哈 反正不要找我 我很很很很菜的
> > 
> > 
> > 这梗过不去了hhhhhhhh
> 
> hhhhhhhhhhhhhhhhh

无限套娃这很凎

**Comment by APJifengc** [comment]
> 
> 
> > > > > 不过啥时候出个jvavscript，虽然两者关联及其微小。
> > > > > C--啊pythan啊HPH啊HTNL啊SCC啊Myspl乱七八糟的，最好再出个Liunx，有了这些，然后进军移动领域：Anbread和l(L)OS。光有软件肯定是不行的，最好研究一下微处理器，名字我想好了，就叫“低堵-哓龙”好了，这是移动端，pc端可以叫嘤特尔(intal)-库刻。啥显卡啊内存啊储存啊乱七八糟的先不着急
> > > > 
> > > > 
> > > > 你可以尝试去写一下...
> > > > 不过在浏览器中被标为`text/jvavscript`应该还会根据 JavaScript 继续执行代码。
> > > > 因此...我觉得将 JavaScript 混淆后当作 JvavScript 可能还不错（？
> > > 
> > > 
> > > 像jQuery这类打包成一个库我觉得也星
> > 
> > 
> > 哈哈哈 反正不要找我 我很很很很菜的
> 
> 这梗过不去了hhhhhhhh

hhh 不说了不说了 要不然tzg又要催我做JVAV了

**Comment by TheZihanGu** [comment]
> > > > > > 不过啥时候出个jvavscript，虽然两者关联及其微小。
> > > > > > C--啊pythan啊HPH啊HTNL啊SCC啊Myspl乱七八糟的，最好再出个Liunx，有了这些，然后进军移动领域：Anbread和l(L)OS。光有软件肯定是不行的，最好研究一下微处理器，名字我想好了，就叫“低堵-哓龙”好了，这是移动端，pc端可以叫嘤特尔(intal)-库刻。啥显卡啊内存啊储存啊乱七八糟的先不着急
> > > > > 
> > > > > 
> > > > > 你可以尝试去写一下...
> > > > > 不过在浏览器中被标为`text/jvavscript`应该还会根据 JavaScript 继续执行代码。
> > > > > 因此...我觉得将 JavaScript 混淆后当作 JvavScript 可能还不错（？
> > > > 
> > > > 
> > > > 像jQuery这类打包成一个库我觉得也星
> > > 
> > > 
> > > 哈哈哈 反正不要找我 我很很很很菜的
> > 
> > 
> > 这梗过不去了hhhhhhhh
> 
> hhh 不说了不说了 要不然tzg又要催我做JVAV了

@APJifengc 请 赶 紧 做
（无尽の套娃

**Comment by Qualia-HUANY** [comment]
J v a v, 永 远 滴 神

**Comment by baohong-cn228813509** [comment]
学习Jvav不就业，全额赔


![YB$EI_H WFBA`AX`UCX GO8](https://user-images.githubusercontent.com/63048227/80963497-9210b700-8dfe-11ea-8e75-834797532bb1.png)

**Comment by 24kcsplus** [comment]
> > > > > > > 不过啥时候出个jvavscript，虽然两者关联及其微小。
> > > > > > > C--啊pythan啊HPH啊HTNL啊SCC啊Myspl乱七八糟的，最好再出个Liunx，有了这些，然后进军移动领域：Anbread和l(L)OS。光有软件肯定是不行的，最好研究一下微处理器，名字我想好了，就叫“低堵-哓龙”好了，这是移动端，pc端可以叫嘤特尔(intal)-库刻。啥显卡啊内存啊储存啊乱七八糟的先不着急
> > > > > > 
> > > > > > 
> > > > > > 你可以尝试去写一下...
> > > > > > 不过在浏览器中被标为`text/jvavscript`应该还会根据 JavaScript 继续执行代码。
> > > > > > 因此...我觉得将 JavaScript 混淆后当作 JvavScript 可能还不错（？
> > > > > 
> > > > > 
> > > > > 像jQuery这类打包成一个库我觉得也星
> > > > 
> > > > 
> > > > 哈哈哈 反正不要找我 我很很很很菜的
> > > 
> > > 
> > > 这梗过不去了hhhhhhhh
> > 
> > 
> > hhh 不说了不说了 要不然tzg又要催我做JVAV了
> 
> @APJifengc 请 赶 紧 做
> （无尽の套娃

套娃开始

**Comment by 555jc** [comment]
臣附议

**Comment by baohong-cn228813509** [comment]
艹艹艹👴笑了，jvav这么高级的东西应该受到国家的推崇





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"555jc"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月7日(星期四) 上午8:27
收件人:&nbsp;"TZG-official/Jvav"<Jvav@noreply.github.com&gt;;
抄送:&nbsp;"Block"<228813509@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [TZG-official/Jvav] [建议]Readme中添加其在MC群宣传迷你的事迹 (#21)





 
臣附议

**Comment by APJifengc** [comment]
> 
> 艹艹艹👴笑了，jvav这么高级的东西应该受到国家的推崇
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"555jc"<notifications@github.com&gt;; 发送时间:&nbsp;2020年5月7日(星期四) 上午8:27 收件人:&nbsp;"TZG-official/Jvav"<Jvav@noreply.github.com&gt;; 抄送:&nbsp;"Block"<228813509@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [TZG-official/Jvav] [建议]Readme中添加其在MC群宣传迷你的事迹 (#21) 臣附议 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

草

**Comment by Lzc256** [comment]
> 不过啥时候出个jvavscript，虽然两者关联及其微小。
> C--啊pythan啊HPH啊HTNL啊SCC啊Myspl乱七八糟的，最好再出个Liunx，有了这些，然后进军移动领域：Anbread和l(L)OS。光有软件肯定是不行的，最好研究一下微处理器，名字我想好了，就叫“低堵-哓龙”好了，这是移动端，pc端可以叫嘤特尔(intal)-库刻。啥显卡啊内存啊储存啊乱七八糟的先不着急

jvavscript我写了[滑稽]， [](https://www.jvavscript.xyz)

**Comment by SuperEndermanSM** [comment]
> 不过啥时候出个jvavscript，虽然两者关联及其微小。
> C--啊pythan啊HPH啊HTNL啊SCC啊Myspl乱七八糟的，最好再出个Liunx，有了这些，然后进军移动领域：Anbread和l(L)OS。光有软件肯定是不行的，最好研究一下微处理器，名字我想好了，就叫“低堵-哓龙”好了，这是移动端，pc端可以叫嘤特尔(intal)-库刻。啥显卡啊内存啊储存啊乱七八糟的先不着急

Windwos,deppin,ubantu

**Comment by jjjj233** [comment]
你们搞得我都想去搞++C了

**Comment by Lzc256** [comment]
> 你们搞得我都想去搞++C了

C艹他不香吗

**Comment by RimuruChan** [comment]
c一他不香吗

**Comment by RimuruChan** [comment]
> 学习Jvav不就业，全额赔
> 
> ![YB$EI_H WFBAAXUCX GO8](https://user-images.githubusercontent.com/63048227/80963497-9210b700-8dfe-11ea-8e75-834797532bb1.png)

赔我（滑稽）

**Comment by Lzc256** [comment]
> > 学习Jvav不就业，全额赔
> > ![YB$EI_H WFBAAXUCX GO8](https://user-images.githubusercontent.com/63048227/80963497-9210b700-8dfe-11ea-8e75-834797532bb1.png)
> 
> 赔我（滑稽）

可海星，我也要索赔

**Comment by ForkFG** [comment]
> 不过啥时候出个jvavscript，虽然两者关联及其微小。
> C--啊pythan啊HPH啊HTNL啊SCC啊Myspl乱七八糟的，最好再出个Liunx，有了这些，然后进军移动领域：Anbread和l(L)OS。光有软件肯定是不行的，最好研究一下微处理器，名字我想好了，就叫“低堵-哓龙”好了，这是移动端，pc端可以叫嘤特尔(intal)-库刻。啥显卡啊内存啊储存啊乱七八糟的先不着急

`C--` 不妥。`JavaScript` 最初的名字就是 `C--`

**Comment by RimuruChan** [comment]
> > 不过啥时候出个jvavscript，虽然两者关联及其微小。
> > C--啊pythan啊HPH啊HTNL啊SCC啊Myspl乱七八糟的，最好再出个Liunx，有了这些，然后进军移动领域：Anbread和l(L)OS。光有软件肯定是不行的，最好研究一下微处理器，名字我想好了，就叫“低堵-哓龙”好了，这是移动端，pc端可以叫嘤特尔(intal)-库刻。啥显卡啊内存啊储存啊乱七八糟的先不着急
> 
> `C--` 不妥。`JavaScript` 最初的名字就是 `C--`

长知识了

**Comment by AMIRIOX** [comment]
出个C puls puls吧 就叫C~~(波浪号)
同时~是C++中的析构函数 暂且当成-吧(逃
我觉得还是吧Jvav的编译器好好写写  加一点好点的特性再去进军别的领域

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: 利姆露酱<mailto:notifications@github.com>
发送时间: 2020年5月23日 9:48
收件人: TZG-official/Jvav<mailto:Jvav@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: Re: [TZG-official/Jvav] [建议]Readme中添加其在MC群宣传迷你的事迹 (#21)


不过啥时候出个jvavscript，虽然两者关联及其微小。
C--啊pythan啊HPH啊HTNL啊SCC啊Myspl乱七八糟的，最好再出个Liunx，有了这些，然后进军移动领域：Anbread和l(L)OS。光有软件肯定是不行的，最好研究一下微处理器，名字我想好了，就叫“低堵-哓龙”好了，这是移动端，pc端可以叫嘤特尔(intal)-库刻。啥显卡啊内存啊储存啊乱七八糟的先不着急

C-- 不妥。JavaScript 最初的名字就是 C--

长知识了

―

**Comment by longtrip1** [comment]
这是什么梗啊，我从抖音过来

**Comment by zrzjohn** [comment]
> 张浩扬博士草

江湖之洞来观摩

**Comment by zrzjohn** [comment]
> 这是什么梗啊，我从抖音过来

这个梗起初是在 China 2B2T 服务器交流群产生的。有一个小学生过来宣传一个叫迷你世界的游戏...然后别的网友问他，他自己说「我会Jvav」...这个梗就产生了

**Comment by cheny0y0** [comment]
可以，只要和谐就行

**Comment by MATRIX-feather** [comment]
> > > 学习Jvav不就业，全额赔
> > > ![YB$EI_H WFBAAXUCX GO8](https://user-images.githubusercontent.com/63048227/80963497-9210b700-8dfe-11ea-8e75-834797532bb1.png)
> > 
> > 
> > 赔我（滑稽）
> 
> 可海星，我也要索赔

我也要索赔
![picture](https://user-images.githubusercontent.com/55654482/88457542-1c2a6200-ceba-11ea-91b1-5195836ecfd1.jpg)

**Comment by cheny0y0** [comment]
> > 这是什么梗啊，我从抖音过来
> 
> 
> 
> 这个梗起初是在 我的世界 China 2B2T 服务器交流群产生的。有一个小学生过来宣传一个叫迷你世界的游戏...然后别的网友问他，他自己说「我会Jvav」...这个梗就产生了

所以，TZG-official=张浩扬？

**Comment by cheny0y0** [comment]
> > > > > > > > 不过啥时候出个jvavscript，虽然两者关联及其微小。
> 
> > > > > > > > C--啊pythan啊HPH啊HTNL啊SCC啊Myspl乱七八糟的，最好再出个Liunx，有了这些，然后进军移动领域：Anbread和l(L)OS。光有软件肯定是不行的，最好研究一下微处理器，名字我想好了，就叫“低堵-哓龙”好了，这是移动端，pc端可以叫嘤特尔(intal)-库刻。啥显卡啊内存啊储存啊乱七八糟的先不着急
> 
> > > > > > > 
> 
> > > > > > > 
> 
> > > > > > > 你可以尝试去写一下...
> 
> > > > > > > 不过在浏览器中被标为`text/jvavscript`应该还会根据 JavaScript 继续执行代码。
> 
> > > > > > > 因此...我觉得将 JavaScript 混淆后当作 JvavScript 可能还不错（？
> 
> > > > > > 
> 
> > > > > > 
> 
> > > > > > 像jQuery这类打包成一个库我觉得也星
> 
> > > > > 
> 
> > > > > 
> 
> > > > > 哈哈哈 反正不要找我 我很很很很菜的
> 
> > > > 
> 
> > > > 
> 
> > > > 这梗过不去了hhhhhhhh
> 
> > > 
> 
> > > 
> 
> > > hhh 不说了不说了 要不然tzg又要催我做JVAV了
> 
> > 
> 
> > @APJifengc 请 赶 紧 做
> 
> > （无尽の套娃
> 
> 
> 
> 套娃开始

接力套娃

**Comment by LAOQIANMO** [comment]
> > > > > > > 不过啥时候出个jvavscript，虽然两者关联及其微小。
> > > > > > > C--啊pythan啊HPH啊HTNL啊SCC啊Myspl乱七八糟的，最好再出个Liunx，有了这些，然后进军移动领域：Anbread和l(L)OS。光有软件肯定是不行的，最好研究一下微处理器，名字我想好了，就叫“低堵-哓龙”好了，这是移动端，pc端可以叫嘤特尔(intal)-库刻。啥显卡啊内存啊储存啊乱七八糟的先不着急
> > > > > > 
> > > > > > 
> > > > > > 你可以尝试去写一下...
> > > > > > 不过在浏览器中被标为`text/jvavscript`应该还会根据 JavaScript 继续执行代码。
> > > > > > 因此...我觉得将 JavaScript 混淆后当作 JvavScript 可能还不错（？
> > > > > 
> > > > > 
> > > > > 像jQuery这类打包成一个库我觉得也星
> > > > 
> > > > 
> > > > 哈哈哈 反正不要找我 我很很很很菜的
> > > 
> > > 
> > > 这梗过不去了hhhhhhhh
> > 
> > 
> > hhh 不说了不说了 要不然tzg又要催我做JVAV了
> 
> @APJifengc 请 赶 紧 做
> （无尽の套娃

极限套娃
