### ISSUE TITLE
[Feature request] Linux support needed

### ISSUE THREAD

**Issue by SuperEndermanSM** [TZG-official/Jvav#22]

**Comment by oganesson0512** [comment]
应该只要编译下就行😁 
所以mac os也加上吧（滑稽

**Comment by TheZihanGu** [comment]
目前某位大佬已经写出来Linux版本，但是相较于Windows Version还是少了一些东西...
我将在评估后考虑是否放出此版本。

**Comment by TheZihanGu** [comment]
目前已将 @2006bt 编写的Unix版在官网进行了更新 (#f4a5924).
目前应该已经可以在官网查看到Unix版本的下载了。如果没有看到，请过后在尝试刷新。
