### ISSUE TITLE
[提问]交互式编译器何时可以实现简单逻辑？

### ISSUE THREAD

**Issue by Lampese** [TZG-official/Jvav#23]
如题

**Comment by TheZihanGu** [comment]
这个简单逻辑...可以举几个例子吗

**Comment by Lampese** [comment]
逻辑语句/运算


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"TheZihanGu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月22日(星期三) 下午5:24
收件人:&nbsp;"TZG-official/Jvav"<Jvav@noreply.github.com&gt;;
抄送:&nbsp;"1523284180"<1523284180@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [TZG-official/Jvav] [提问]交互式编译器何时可以实现简单逻辑？ (#23)





 
这个简单逻辑...可以举几个例子吗

**Comment by TheZihanGu** [comment]
这个功能将在未来的几个版本中实现，请关注网站下载页面的更新。感谢提出这个意见。
