### ISSUE TITLE
你这个主页访问属实慢

### ISSUE THREAD

**Issue by MyDandan233** [TZG-official/Jvav#25]
发个恰饭码出来我资助你买台新主机好不好

**Comment by MyDandan233** [comment]
所有jvav下载Windows的不应该叫latest.zip吗

**Comment by MyDandan233** [comment]
![Uploading QQ截图20200422203636.png…]()
![4IYVI1YQKYUBP@`M2J3J F8](https://user-images.githubusercontent.com/42466144/79982532-1139ed00-84d9-11ea-96b7-0961a1d4cc8d.png)

**Comment by TheZihanGu** [comment]
![Screenshot-2020-04-23上午7 55 26](https://user-images.githubusercontent.com/39030261/80044694-e468f280-8537-11ea-971a-ff006f176329.png)

**Comment by TheZihanGu** [comment]
服务器不考虑更换。而且我们的目的也并非「访问速度快」，而是「能访问」。使用cloudflare加速。
如果您想捐赠，那么我们会考虑将这些钱用在购买cloudflare Pro计划上。
捐赠请发送邮件到[zihangu@tzg6.tech](mailto:zihangu@tzg6.tech)
