### ISSUE TITLE
【问题】在什么是jvav页面上有一个VAPE和VPAE

### ISSUE THREAD

**Issue by CRE-Official** [TZG-official/Jvav#33]
RT

**Comment by TheZihanGu** [comment]
如果你指的是「什么是 Jvav？」页面的这段话：
>Vape 是由 张浩扬 博士使用 Jvav 编写的秒注入式黑客软件。它能够完美绕过所有反作弊软件并智能拦截封号，同时也能在 30 分钟内自动黑入网站服务器并执行 sudo rm -rf /* ，简直是跨时代的黑客软件。

Vape 出自百度贴吧[jvav是世界上最好的语言，他能编写最好的客户端，遇到黑客自](https://tieba.baidu.com/p/6627454633)。当时在找灵感的时候发现了这一篇帖子，就把 Vape 这个概念加入到了这个页面。
原文是这样写的：
>jvav是世界上最好的语言，他能编写最好的客户端，遇到黑客自动注入vpae，vpae是是张浩扬大神编写的秒注入式黑客，完美绕过所有反作弊，智能拦截封号，遇到黑客不要怕！拉满打回去

**Comment by TheZihanGu** [comment]
哦我看错了...你应该指的是这里的 Vpae。
>如果您在计算机上收到了 Jvav 的加密勒索通知但您记得从未下载或安装它，则有可能是 张浩扬 博士正在使用 Jvav 对您的计算机进行 Vpae。

这个的确是写错了，感谢提醒。稍后将会对此处进行修改。

**Comment by TheZihanGu** [comment]
目前已经修复这个拼写错误。你可以在 eaee9bd 查看详情。
