### ISSUE TITLE
我可以fork一份代码到一个github账户上再整一个jvav网站吗？

### ISSUE THREAD

**Issue by kurisucat** [TZG-official/Jvav#38]
**如题。**
账号 Github 地址：https://github.com/Jvav-Official
感谢张浩扬博士的 Jvav 的编程语言，很好用！
jvav.run (目前正在审核域名中)

**Comment by TTomDuan** [comment]
多一个有什么用。
java官网难道还有两个么

**Comment by kurisucat** [comment]
弄一些比较离谱一些的网页上去

**Comment by TTomDuan** [comment]
那可以，我以后去fork你/斜眼笑

**Comment by TheZihanGu** [comment]
我感觉整这么多Jvav网站没有必要...
如果你想弄一些靠谱的Jvav网站到上面，直接引到相应的网站不就好了...
如果你还有其他理由，可以继续说明。

**Comment by kurisucat** [comment]
> 我感觉整这么多Jvav网站没有必要...
> 如果你想弄一些靠谱的Jvav网站到上面，直接引到相应的网站不就好了...
> 如果你还有其他理由，可以继续说明。

知道了
这就去CNAME到该域名

**Comment by TheZihanGu** [comment]
? 你CNAME并没有用的...
人类迷惑行为大赏

**Comment by TheZihanGu** [comment]
这边在其他站点使用我代码的请求已经无效。若要重新申请，请再开Issues。
