### ISSUE TITLE
Dr. Zhang有计划推出JvavFroLxuni吗

### ISSUE THREAD

**Issue by AkinoMaple** [TZG-official/Jvav#39]
Lxuni用户痛哭  
另外Jvav4Unix存在含有MACOSX这个不必要且痛击无产阶级的目录

**Comment by TheZihanGu** [comment]
你可以考虑自己写一个（？

**Comment by AkinoMaple** [comment]
> 你可以考虑自己写一个（？

可以有，我打算写Jvav Go和Jvav Rust

**Comment by AkinoMaple** [comment]
[Go Jvav](https://github.com/AkinoMaple/go-jvav)开写力，不过好像本来就有……go.java
