### ISSUE TITLE
新 名 言 (Jaba)

### ISSUE THREAD

**Issue by sfubuki5** [TZG-official/Jvav#40]
据说是这位小学生的新名言
![1b6d9d22efa8c848](https://user-images.githubusercontent.com/62366679/80601234-1d392800-8a60-11ea-9e12-7ec2df5034ea.jpg)

**Comment by TheZihanGu** [comment]
此截图无从查证...

**Comment by kurisucat** [comment]
> 此截图无从查证...

哔哩哔哩上有，说是有人邀请去他们群，然后一堆人说想要教他们去学jvav，然后张浩洋博士改口说他会jaba。
（后改正写java（终于正确了））

**Comment by TheZihanGu** [comment]
> > 此截图无从查证...
> 
> 哔哩哔哩上有，说是有人邀请去他们群，然后一堆人说想要教他们去学jvav，然后张浩洋博士改口说他会jaba。
> （后改正写java（终于正确了））

然后我又去注册jaba.tech了...准备跳转jvav.top（

**Comment by chenai-spec** [comment]
> > > 此截图无从查证...
> > 
> > 
> > 哔哩哔哩上有，说是有人邀请去他们群，然后一堆人说想要教他们去学jvav，然后张浩洋博士改口说他会jaba。
> > （后改正写java（终于正确了））
> 
> 然后我又去注册jaba.tech了...准备跳转jvav.top（

刚刚在b站看到评论区有这个梗，百度一查，才知道怎么回事...

**Comment by kurisucat** [comment]
> > > 此截图无从查证...
> > 
> > 
> > 哔哩哔哩上有，说是有人邀请去他们群，然后一堆人说想要教他们去学jvav，然后张浩洋博士改口说他会jaba。
> > （后改正写java（终于正确了））
> 
> 然后我又去注册jaba.tech了...准备跳转jvav.top（

我的网站已经饥渴难耐了 _/斜眼笑_
![image](https://user-images.githubusercontent.com/64016189/80720120-0dd4e000-8b2f-11ea-8337-932f5d5eeb1a.png)
（https://www.ojbkle.xyz/）

**Comment by chenai-spec** [comment]
> > > > 此截图无从查证...
> > > 
> > > 
> > > 哔哩哔哩上有，说是有人邀请去他们群，然后一堆人说想要教他们去学jvav，然后张浩洋博士改口说他会jaba。
> > > （后改正写java（终于正确了））
> > 
> > 
> > 然后我又去注册jaba.tech了...准备跳转jvav.top（
> 
> 我的网站已经饥渴难耐了 _/斜眼笑_
> ![image](https://user-images.githubusercontent.com/64016189/80720120-0dd4e000-8b2f-11ea-8337-932f5d5eeb1a.png)
> （https://www.ojbkle.xyz/）

神tm假骨文。哈哈

**Comment by AgentOfLyra** [comment]
这个还真有可能是打错的，26键b和v挨得挺近的

**Comment by Dtue** [comment]
> > > > 此截图无从查证...
> 
> > > 
> 
> > > 
> 
> > > 哔哩哔哩上有，说是有人邀请去他们群，然后一堆人说想要教他们去学jvav，然后张浩洋博士改口说他会jaba。
> 
> > > （后改正写java（终于正确了））
> 
> > 
> 
> > 然后我又去注册jaba.tech了...准备跳转jvav.top（
> 
> 
> 
> 我的网站已经饥渴难耐了 _/斜眼笑_
> 
> ![image](https://user-images.githubusercontent.com/64016189/80720120-0dd4e000-8b2f-11ea-8337-932f5d5eeb1a.png)
> 
> （[https://www.ojbkle.xyz/](https://www.ojbkle.xyz/)）
> 
> 

噗哈哈哈哈哈哈哈哈哈哈哈ojbkle可海星
