### ISSUE TITLE
O J B K L E 假 古 文 自 荐（推荐将右下角改为 ojbkle.xyz）

### ISSUE THREAD

**Issue by kurisucat** [TZG-official/Jvav#42]
如题。

-----------原提问-----------
已将 Jvav 下载地址指向 https://jvav.top。
![宣传图](https://user-images.githubusercontent.com/64016189/80678183-04c31f00-8aed-11ea-9a3d-0a7442631248.png)
[进  入  官  网](https://www.jvav.run/)
做了几个离谱的话语。
我做这个也就图一乐。/斜眼笑
©Ojbkle 2020

**Comment by TheZihanGu** [comment]
......
你这还不如把腾讯课堂的页面做一下...

**Comment by kurisucat** [comment]
> ......
> 你这还不如把腾讯课堂的页面做一下...

好，我改进一下

**Comment by TheZihanGu** [comment]
So why...
并且本站的 Oracle 标志已经在 d0f733d 进行删除，并不考虑重新加入。

**Comment by TheZihanGu** [comment]
So why...
并且本站的 Oracle 标志已经在 d0f733d 进行删除，并不考虑重新加入。
