### ISSUE TITLE
jvav编译器运行提示缺少DLL

### ISSUE THREAD

**Issue by duoduo2333** [TZG-official/Jvav#44]
![Snipaste_2020-05-01_09-45-05](https://user-images.githubusercontent.com/61302211/80774822-98016080-8b90-11ea-9ff2-afb6ea055f9f.jpg)
![Snipaste_2020-05-01_09-45-40](https://user-images.githubusercontent.com/61302211/80774828-9afc5100-8b90-11ea-9b08-1da94ceb87e8.jpg)

**Comment by TheZihanGu** [comment]
建议查看是否缺少C++运行库，或通过[百度](https://nbhbdm.cn)搜索解决方法。
