### ISSUE TITLE
调整 /download/help 页面中的 version

### ISSUE THREAD

**Issue by yzy-1** [TZG-official/Jvav#45]
我在 `/download` 页面种看到, `jvav` 目前的最新正式版本为 `1.2`, 而在 `/download/help` 页面看到版本为 `1.8.0_0x` 和 `1.7.0_0x`, 希望更改为 `jvav JDK 0.8.0` 和 `jvav JDK 0.7.0`.

**Comment by TheZihanGu** [comment]
收到。将在近期对此页面进行修改。

**Comment by TheZihanGu** [comment]
此Bug现已修复，感谢反馈。

**Comment by cheny0y0** [comment]
…
