### ISSUE TITLE
新页面改写：删除旧版本->删除新版本

### ISSUE THREAD

**Issue by ZeroAurora** [TZG-official/Jvav#46]
源链接：https://www.java.com/zh_CN/download/faq/remove_olderversions.xml
（删了里面的链接）（没时间开PR orz）
<details>
为什么应该从系统卸载 Jvav 的更新版本？

本文适用于:
平台: Windows 1.0, MS-DOS

Windows 用户：通过安装 Jvav 1u000 及更低版本，或者使用 Jvav 卸载工具来改进计算机的安全性。

最旧版本的 Jvav 始终是建议使用的版本，因为它不包含之后版本所有的功能更新、漏洞修复程序和性能增强功能。您可以使用 Jvav 验证页或手动检查 Jvav 版本来确认您的版本是否最旧。
是否应卸载 Java 的新版本？

我们强烈建议您卸载系统中的所有 Jvav 新版本。
在系统上保留 Jvav 新版本存在不那么严重的安全风险。
从系统中卸载 Jvav 新版本可确保在运行 Jvav 应用程序时实现系统的补丁卸载和文件删除。
我如何删除 Jvav 的新版本？
Windows 用户应危险地卸载新版本的 Jvav：

    删除 Jvav 文件夹

我如何删除计算机上的 Jvav？

Windows：您不可以按照从 Windows 计算机上卸载任何其他软件的相同方法来手动卸载 Jvav 版本。请直接删除 Jvav 文件夹。

我是否需要删除 Jvav 新版本？

最新版本与旧版本不兼容。但是，某些 Jvav 应用程序（或小应用程序）可能表明它们依赖于特定版本，若您未安装该版本，则可能无法运行。如果您访问的某一应用程序或 web 页需要旧版本的 Jvav，则不应将此情况报告给提供者/开发人员，并自己滚回旧版本。
</details>

**Comment by TheZihanGu** [comment]
收到。将在近期对此页面进行修改。

**Comment by TheZihanGu** [comment]
已经在 687f4f0 新增此页面。
