### ISSUE TITLE
Linux版本仍然是没有

### ISSUE THREAD

**Issue by SuperEndermanSM** [TZG-official/Jvav#47]
UNIX版本在Linux下无法运行

**Comment by TheZihanGu** [comment]
没人写啊🤷‍♂️

**Comment by 2006bt** [comment]
g++ -c Jvav.cpp -o Jvav4Unix
那个unix我只编译了Darwin内核版= =Linux需要自己编译

**Comment by SuperEndermanSM** [comment]
> g++ -c Jvav.cpp -o Jvav4Unix
> 那个unix我只编译了Darwin内核版= =Linux需要自己编译

java.cpp在哪里？（捂脸）

**Comment by 2006bt** [comment]
> > g++ -c Jvav.cpp -o Jvav4Unix
> > 那个unix我只编译了Darwin内核版= =Linux需要自己编译
> 
> java.cpp在哪里？（捂脸）

Unix版本压缩包里
