### ISSUE TITLE
可否考虑将图片等资源外置？

### ISSUE THREAD

**Issue by Anilople** [TZG-official/Jvav#48]
git中的图片好多，下载一次要好久。

压缩包的大小为28M，以后图片更多时，这个大小还会增加。

可否考虑将图片上传到图床？

**Comment by TheZihanGu** [comment]
因为避免其他网站热链接本站资源，因此不考虑资源外置。
您下载GitHub压缩包时的速度取决于您连接到GitHub的速度，与Jvav.top并没有任何关系。
请您尝试科学上网等方法。
