### ISSUE TITLE
建议让Jvav变成Pinyin

### ISSUE THREAD

**Issue by Lapis-Apple** [TZG-official/Jvav#50]
Xiande Geng Zhanghaoyang , hai geng zhong guo.
显得更张浩洋 还更中国

**Comment by TheZihanGu** [comment]
?

**Comment by Lapis-Apple** [comment]
output -> shuchu
input -> shuru
leave -> likai
之类的

**Comment by Lapis-Apple** [comment]
Weishenme bu ne? zhe benlai ye bushi zhengjing ruanjian.
