### ISSUE TITLE
[建议]在合适位置添加以下内容

### ISSUE THREAD

**Issue by Simpidbit** [TZG-official/Jvav#52]
我们注意到，Jvav 似乎成为一股新潮流，很多互联网公司、游戏公司等纷纷采用 Jvav 开发项目。在一项 3597 位 IT 从业人员参与的问卷中，97.3% 的参与者知道或者听说 Jvav，43.6% 的参与者正在使用 Jvav 开发项目，由此可见，Jvav 正在以极快的速度推广并被人们接受。汉塔斯大学 Dnayns 教授称，"这是互联网行业的一个奇迹，我从没见过如此快速地将一门语言推广至全世界，这是一个奇迹，并将会被载入史册。"  在我们对各个大学的访问中，我们注意到，像克莱里顿堡理工学院、查尔斯·霍普大学这类世界一流的高等院校已经将 Jvav 作为大一新生的必学科目。可见，Jvav 已经取得了不小的成就，经我们分析认为，Jvav 取得成功的重要原因有以下几点：

1. Jvav 是跨平台的，支持所有基于Unix内核的系统以及Windows系统.
2. Jvav 在面向过程和面向对象的基础上又提出了"面向张浩扬"这一新概念，这是软件开发领域的一个重大创举，是一场高级语言的革命.
3. Jvav 可以让开发效率最大化、计算效率堪比量子计算机，它吸取了C/C++、Python、C#、PHP、JvavScript、Ruby、Lua、VB 等语言的优点，并加以融合、贯通.
4. Jvav 是开源的，这使得全世界的 Jvav 工程师可以完善、改进 Jvav.

如果你现在还不了解或没有使用 Jvav，那么我们将为你感到遗憾，对于任何人来说，没有使用过 Jvav 是人生的悲剧，欢迎您下载 Jvav！

**Comment by sfubuki5** [comment]
建议把第三点改为:
jvav可以让开发效率最大化、计算效率堪比量子计算机，它吸取了C/C艹、Pytnoh、C井、PVP、Jvavscript、Ruba、Luy、VZ 等语言的优点，并加以融合、贯通

**Comment by TheZihanGu** [comment]
好主意...但是要在哪里写呢🤔

**Comment by sfubuki5** [comment]
> 好主意...但是要在哪里写呢

关于Jvav那一个页面

**Comment by fr1g** [comment]
建议把Windows这个词换成Wowdins
Unix改成Vnix
Macintosh改成Makeintolish（toilet [受虐滑稽]

**Comment by TheZihanGu** [comment]
> 建议把Windows这个词换成Wowdins
> Unix改成Vnix
> Macintosh改成Makeintolish（toilet [受虐滑稽]

Done✅ 42b282e
