### ISSUE TITLE
对于支持页面一些恶搞的建议

### ISSUE THREAD

**Issue by xiaopangju** [TZG-official/Jvav#59]
由于个人不会写代码，所以开个issue，来写一下支持页面（Java.com地址：https://www.java.com/zh_CN/download/support.jsp）的恶搞建议
（破折号前面的是java网站上的原文，破折号后面的是恶搞的）
安装java——删除jvav
删除旧版本——删除新版本
禁用java——启用jvav
java答疑解难——jvav有效文章
使用java——卸载jvav
不对java的最终用户提供电话支持——对jvav最终用户提供专业的张浩洋支持
电话支持——张浩洋支持
	Java.com 上的帮助和常见问题部分提供了用户最常遇到的问题的解答。此处提供的解决方案使用分步说明，易于遵循和实施。这可能是解决您问题的最快方式。这些部分将基于我们从用户收到的反馈定期进行更新。——jvav.top上的帮助和不常见问题部分提供了没有用户遇到的问题的解答。此处提供的解决方案不方便说明，不容易遵循和实施，这可能解决您的问题。这些问题都没有用户遇到过。
使用者 Java 反馈——用户jvav反馈

**Comment by TheZihanGu** [comment]
收到。将在近期添加此页面。

**Comment by TheZihanGu** [comment]
已经在 67d35ef bf238dd 新增此页面。
