### ISSUE TITLE
脑洞建议

### ISSUE THREAD

**Issue by 24kcsplus** [TZG-official/Jvav#61]
建议添加语言界面，最好用谷歌生草机来翻译

**Comment by TheZihanGu** [comment]
我个人认为似乎没有什么必要...

**Comment by xiaopangju** [comment]
但是，现在页面底下那个支持点进去貌似是404的，我想为这个页面贡献内容（不会写代码只能这么做了）

已从 Outlook Mobile<https://aka.ms/blhgte> 发送

________________________________
发件人: TheZihanGu <notifications@github.com>
发送时间: 2020年5月5日星期二 03:05
收件人: TZG-official/Jvav
抄送: Subscribed
主题: Re: [TZG-official/Jvav] 脑洞建议 (#61)


我个人认为似乎没有什么必要...

―

**Comment by 24kcsplus** [comment]
> 我个人认为似乎没有什么必要...

emmmmmmmmmm,添加拼音怎么样
或者拼音英语，语言选项卡就像这样
选择语言
xuanzeyuyan
chusi e langeruiju

中文
pinyin
yinggelixu

**Comment by TheZihanGu** [comment]
> 但是，现在页面底下那个支持点进去貌似是404的，我想为这个页面贡献内容（不会写代码只能这么做了） 已从 Outlook Mobile<https://aka.ms/blhgte> 发送
> […](#)

支持已经有了啊……

**Comment by xiaopangju** [comment]
我发那句话的时候还没有，似乎有一丁点和我的脑洞合上了

已从 Outlook Mobile<https://aka.ms/blhgte> 发送

________________________________
发件人: TheZihanGu <notifications@github.com>
发送时间: 2020年5月5日星期二 14:48
收件人: TZG-official/Jvav
抄送: bingchuanjuzi; Comment
主题: Re: [TZG-official/Jvav] 脑洞建议 (#61)


但是，现在页面底下那个支持点进去貌似是404的，我想为这个页面贡献内容（不会写代码只能这么做了） 已从 Outlook Mobilehttps://aka.ms/blhgte 发送
…

支持已经有了啊……

―

**Comment by fr1g** [comment]
有精力的就留语言梗了 未来甚至有希望发展成玩梗中心[受虐滑稽]
