### ISSUE TITLE
风险

### ISSUE THREAD

**Issue by fr1g** [TZG-official/Jvav#63]
我打不开免责声明啊
而且直接把自然人的脸和名字直接贴上去 好像...
在法理上不太合适...
所以建议早点把免责声明写出来 避免不必要的麻烦
另：我最近在Wowdins操作系统上安装了jvav，感觉良好
[受虐滑稽]

**Comment by fr1g** [comment]
啊还有 为什么点条款还是会到Oracle的网站？

**Comment by fr1g** [comment]
还有就是 捐赠页面的问题...因为页面本身玩梗的时候就涉及到一些很打擦边球的行为，还来个捐赠页面直接放在这里...万一 我说万一 出了点岔子要被查的话 可能会被视为“侵犯他人权利并谋取利益”
对。“谋取利益”。别忘了pandownload的作者是以什么理由被抓的

**Comment by TheZihanGu** [comment]
PD人家网站ICP备案了想查他也很容易吧...
免责声明那里还没做。并且我问过张浩扬本人 他似乎并不阻止这种玩梗的行为。
鬼知道呢...🤷‍♂️

**Comment by TheZihanGu** [comment]
而且如果真的算「以盈利为目的侵犯肖像权」那也只是民事责任吧...

**Comment by fr1g** [comment]
？没想到本人会“并不阻止”
妈耶 [受虐滑稽]
还有，ojbkle那个站也是你做的吗？我是看到那上面的照片有作处理才想到这方面的问题的。
[民法不是法吗！（半恼]

**Comment by TheZihanGu** [comment]
ojbkle不是我的，是 @kurisucat 做的，详见[https://github.com/TZG-official/Jvav/issues/42](O J B K L E 假 古 文 自 荐(推荐将右下角改为 ojbkle.xyz))
至少...不用负更大的责任🤔
我这边用的图片基本上都是原图（扣背景），没有做什么恶搞。

**Comment by kurisucat** [comment]
本人不请自来，zhy 的想法是笑梗不笑人，具体的话我可以去换一张没有争议的图片

**Comment by fr1g** [comment]
那倒整挺好 未来会加类似梗进去吗？

**Comment by TheZihanGu** [comment]
> 那倒整挺好 未来会加类似梗进去吗？

...?
