### ISSUE TITLE
jvav.top咋被暂停了？

### ISSUE THREAD

**Issue by SiberiaApp** [TZG-official/Jvav#66]
包括隔壁的jvav.net也变了风格，发生了啥事？

**Comment by danuonuo** [comment]
仅供参考：有人说这个网站就是破解别人启动器那个，源站ip暴露了（但是这个页面不是GitHub pages么）

**Comment by xiaopangju** [comment]
#67

**Comment by Dobby233Liu** [comment]
> （但是这个页面不是GitHub pages么）

好像[是用Netlify的](https://github.com/TZG-official/Jvav/blob/68e6267d33bb0de1559af02792779983cff60fb5/ga/js/console.js#L14)

**Comment by TheZihanGu** [comment]
由于Netlify被恶意刷流量，因此导致站点被暂停。
目前已经更换服务器，现已恢复访问。
