### ISSUE TITLE
jvav.top已经无法访问

### ISSUE THREAD

**Issue by danuonuo** [TZG-official/Jvav#67]

**Comment by SiberiaApp** [comment]
jvev.net的风格也变了...

**Comment by SiberiaApp** [comment]
jvav.net的风格也变了...

**Comment by danuonuo** [comment]
> jvav.net的风格也变了...

据说是在知乎上被谴责了，可能还和mc启动器事件有关系

**Comment by SiberiaApp** [comment]
> > jvav.net的风格也变了...
> 
> 据说是在知乎上被谴责了，可能还和mc启动器事件有关系

mc启动器事件是啥？求科普[doge]

**Comment by danuonuo** [comment]
> > > jvav.net的风格也变了...
> > 
> > 
> > 据说是在知乎上被谴责了，可能还和mc启动器事件有关系
> 
> mc启动器事件是啥？求科普[doge]

https://zhuanlan.zhihu.com/p/139114864

**Comment by xiaopangju** [comment]
#66

**Comment by xiaopangju** [comment]
#66 jvav.top咋被暂停了

**Comment by TheZihanGu** [comment]
由于Netlify被恶意刷流量，因此导致站点被暂停。
目前已经更换服务器，现已恢复访问。

**Comment by fancyQu** [comment]
qq交流群搜不到
