### ISSUE TITLE
请求删除我之前提供的脑洞文字

### ISSUE THREAD

**Issue by xiaopangju** [TZG-official/Jvav#69]
我就是看到mcbbs上的[帖子](https://www.mcbbs.net/forum.php?mod=viewthread&tid=1042063&mobile=2) ，我怕被人肉，以及被建灵堂，请求删除之前我贡献的脑洞文字

**Comment by danuonuo** [comment]
不要怕，据说那个阿里工程师就是个初中生。知乎的审核太。。。。
