### ISSUE TITLE
无法启动程序，错误代码0xc000007b

### ISSUE THREAD

**Issue by fancyQu** [TZG-official/Jvav#71]
![批注 2020-05-13 192346](https://user-images.githubusercontent.com/65284374/81806622-491fd780-954f-11ea-9d28-940e4693608e.png)

**Comment by fancyQu** [comment]
还有，就是QQ交流群（1095640864）好像搜不到

**Comment by SiberiaApp** [comment]
试试微软运行库？

**Comment by TheZihanGu** [comment]
> 还有，就是QQ交流群（1095640864）好像搜不到

由于部分「闲人」恶意加群嘲讽，因此已关闭群搜索并禁止加群。开放时间待定。

**Comment by TheZihanGu** [comment]
目前官网分发的版本由 @30266-Official 开发。
由 TZG-official 及其他成员开发的 Jvav 位于 [TZG-official/Jvav-Windows](https://github.com/TZG-official/Jvav-Windows)，此项目仅为官网源码。
