### ISSUE TITLE
发表意见

### ISSUE THREAD

**Issue by aliflyingfish** [TZG-official/Jvav#72]
不得不承认，你的想法确实很新颖，你的编程技术还有待提高，即使我是CSharp的开发人员，几乎和你的年龄一样，但是你的代码还有所欠缺，你完全可以开发出（正经的）C++程序，并且你的0x000007b错误是可以修正的。你一定可以完成

**Comment by Dobby233Liu** [comment]
应转移到 https://github.com/TZG-official/Jvav-Windows

**Comment by TheZihanGu** [comment]
目前官网分发的版本由 @30266-Official 开发。
由 TZG-official 及其他成员开发的 Jvav 位于 [TZG-official/Jvav-Windows](https://github.com/TZG-official/Jvav-Windows)，此项目仅为官网源码。
