### ISSUE TITLE
针对0x000007b的可能的解决方案

### ISSUE THREAD

**Issue by aliflyingfish** [TZG-official/Jvav#73]
我们发现你的程序根目录下具有动态链接库（msvcp104d）请尝试在你的解决方案下重定向msvcp104d.dll使用相对路径

**Comment by TheZihanGu** [comment]
目前官网分发的版本由 @30266-Official 开发。
由 TZG-official 及其他成员开发的 Jvav 位于 [TZG-official/Jvav-Windows](https://github.com/TZG-official/Jvav-Windows)，此项目仅为官网源码。
