### ISSUE TITLE
问一下pr发生了什么？

### ISSUE THREAD

**Issue by yuzijiang1093883** [TZG-official/Jvav#80]
pr交不上去了

**Comment by TheZihanGu** [comment]
Pull Request: #83 
你这不是交上去了么...

**Comment by xiaopangju** [comment]
我觉得ke'neng可能是网速原因
________________________________
发件人: TheZihanGu <notifications@github.com>
发送时间: 2020年5月22日 18:38
收件人: TZG-official/Jvav <Jvav@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: Re: [TZG-official/Jvav] 问一下pr发生了什么？ (#80)


Pull Request: #83<https://github.com/TZG-official/Jvav/pull/83>
你这不是交上去了么...

―
