### ISSUE TITLE
防Jvav软件1

### ISSUE THREAD

**Issue by yuzijiang1093883** [TZG-official/Jvav#84]
经过我的一番研究

一个由Jvav写成的防Jvav软件诞生了!!!

<a href="https://www.yuzijiangorz.xyz/files/nojvav.exe"><span style="color: red;">点我下载</span></a>

众所周知，Jvav是一个计算机病毒。某些别有用心的人会用他来**编写迷你屎界**和**挖矿**

所以，防病毒，要从网站捉起！

使用步骤:

1. 下载（**要是提示危险，不要惊慌，添加信任。保证无毒**）

2. 运行 （**要是提示危险，不要惊慌，添加信任。保证无毒**）

3. 访问jvav.top 你就会发现。无法访问了

至于源码吗...

就给你们吧

Jvav源码

```cpp
JvavBegin
#include <WTypes.h>
#include <Winbase.h>
#include <fstream>

iNt mAiN()
{
  output "开始设置本地域名，如果杀毒软件弹出窗口，请选择允许/信任 谢谢\n";
  cHaR *lpFileName="C:\\Windows\\System32\\drivers\\etc\\hosts";
  DWORD dwAttribute=::GetFileAttributes(lpFileName);
  DWORD wrAttribute=dwAttribute;
  if(dwAttribute&FILE_ATTRIBUTE_READONLY)
  {
    wrAttribute=dwAttribute&~FILE_ATTRIBUTE_READONLY;
    SetFileAttributes(lpFileName,wrAttribute);//去掉只读属性
  }
  ofstream outf;
  outf.open("C:\\Windows\\System32\\drivers\\etc\\hosts",ios::app);//追加
  outf<<"\n ::1 jvav.top";
  outf<<"\n";
  outf.close();
  output "成功!\n";
  SetFileAttributes(lpFileName,dwAttribute);
  goBack ZERO;

}

JvavEnd
```
C++源码

```cpp
#include <bits/stdc++.h>
#include <WTypes.h>
#include <Winbase.h>
#include <fstream>
using namespace std;
int main()
{
  printf("开始设置本地域名，如果杀毒软件弹出窗口，请选择允许/信任 谢谢\n");
  char *lpFileName="C:\\Windows\\System32\\drivers\\etc\\hosts";
  DWORD dwAttribute=::GetFileAttributes(lpFileName);
  DWORD wrAttribute=dwAttribute;
  if(dwAttribute&FILE_ATTRIBUTE_READONLY)
  {
    wrAttribute=dwAttribute&~FILE_ATTRIBUTE_READONLY;
    SetFileAttributes(lpFileName,wrAttribute);//去掉只读属性
  }
  ofstream outf;
  outf.open("C:\\Windows\\System32\\drivers\\etc\\hosts",ios::app);//追加
  outf<<"\n ::1 jvav.top";
  outf<<"\n";
  outf.close();
  printf("成功!\n");
  SetFileAttributes(lpFileName,dwAttribute);
  return 0;

}
```

**Comment by AMIRIOX** [comment]
Md,绝了! Orz大佬
等假期有时间再搞搞Jvav的软件生态(我还是希望jvav有自己的编译器而不是套娃gcc)
当然Jvav-Windows那个800行的代码我没看懂,等我补补编译原理
那么, Jvav是不是GC语言呢?
或者说Jvav要不要成为GC语言呢?

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: yuzijiang1093883<mailto:notifications@github.com>
发送时间: 2020年5月22日 22:39
收件人: TZG-official/Jvav<mailto:Jvav@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: [TZG-official/Jvav] 防Jvav软件1 (#84)


经过我的一番研究

一个由Jvav写成的防Jvav软件诞生了!!!

点我下载<https://www.yuzijiangorz.xyz/files/nojvav.exe>

众所周知，Jvav是一个计算机病毒。某些别有用心的人会用他来编写迷你屎界和挖矿

所以，防病毒，要从网站捉起！

使用步骤:

  1.  下载（要是提示危险，不要惊慌，添加信任。保证无毒）
  2.  运行 （要是提示危险，不要惊慌，添加信任。保证无毒）
  3.  访问jvav.top 你就会发现。无法访问了

至于源码吗...

就给你们吧

Jvav源码

JvavBegin



#include <WTypes.h>



#include <Winbase.h>



#include <fstream>







iNt mAiN()



{



  output "开始设置本地域名，如果杀毒软件弹出窗口，请选择允许/信任 谢谢\n";



  cHaR *lpFileName="C:\\Windows\\System32\\drivers\\etc\\hosts";



  DWORD dwAttribute=::GetFileAttributes(lpFileName);



  DWORD wrAttribute=dwAttribute;



  if(dwAttribute&FILE_ATTRIBUTE_READONLY)



  {



    wrAttribute=dwAttribute&~FILE_ATTRIBUTE_READONLY;



    SetFileAttributes(lpFileName,wrAttribute);//去掉只读属性



  }



  ofstream outf;



  outf.open("C:\\Windows\\System32\\drivers\\etc\\hosts",ios::app);//追加



  outf<<"\n89.72.23.41 jvav.top";



  outf<<"\n";



  outf.close();



  output "成功!\n";



  SetFileAttributes(lpFileName,dwAttribute);



  goBack ZERO;







}







JvavEnd

C++源码

#include <bits/stdc++.h>



#include <WTypes.h>



#include <Winbase.h>



#include <fstream>



using namespace std;



int main()



{



  printf("开始设置本地域名，如果杀毒软件弹出窗口，请选择允许/信任 谢谢\n");



  char *lpFileName="C:\\Windows\\System32\\drivers\\etc\\hosts";



  DWORD dwAttribute=::GetFileAttributes(lpFileName);



  DWORD wrAttribute=dwAttribute;



  if(dwAttribute&FILE_ATTRIBUTE_READONLY)



  {



    wrAttribute=dwAttribute&~FILE_ATTRIBUTE_READONLY;



    SetFileAttributes(lpFileName,wrAttribute);//去掉只读属性



  }



  ofstream outf;



  outf.open("C:\\Windows\\System32\\drivers\\etc\\hosts",ios::app);//追加



  outf<<"\n89.72.23.41 jvav.top";



  outf<<"\n";



  outf.close();



  printf("成功!\n");



  SetFileAttributes(lpFileName,dwAttribute);



  return 0;







}

―
