### ISSUE TITLE
发现Jvav并没有Lvinx(Linux)版本

### ISSUE THREAD

**Issue by yuzijiang1093883** [TZG-official/Jvav#87]
目前正在写Lvinx版本

**Comment by XWVIKE** [comment]
不是有vnix版本么 反倒是没有mca版本。

**Comment by TheZihanGu** [comment]
> 不是有vnix版本么 反倒是没有mca版本。

Unix 版可直接在 Terminal 跑...

**Comment by yuzijiang1093883** [comment]
@TheZihanGu 

Unix版本无法再CentOs上运行

**Comment by TheZihanGu** [comment]
Pull Request: #88 
我们发现你在这些 Commit 中将请将被删除的 Unix 版本进行还原。
