### ISSUE TITLE
请求添加左下角"免责声明"和"开发人员"页面

### ISSUE THREAD

**Issue by AMIRIOX** [TZG-official/Jvav#89]
原因:
1.  目前具有一些批评Jvav"过度玩梗"/"网络暴力",我们并不评判张浩洋事件本身而是专注与开发(玩梗),但为了 一些必要的说明,还是应加上张浩洋本人的意见看法以及免责声明(据作者说张浩洋不介意大家玩这个梗,希望加上截图之类的)
2. 目前有58个fork和37个pull request,希望作者能为这些参与开发的开发者设计一个页面
3. 另外 感觉把页面色调换成蓝色更好 ,展现出我们与Oracle Java的对立(bushi

**Comment by AMIRIOX** [comment]
markdown写炸了

**Comment by TheZihanGu** [comment]
感谢建议！我们将在近日进行增加。

**Comment by TheZihanGu** [comment]
免责声明：#42b282e

**Comment by TheZihanGu** [comment]
免责声明已经安排了！#0022358

**Comment by TheZihanGu** [comment]
「开发人员」页面命名为「贡献者」，并已提交 Commit. 1853f48

**Comment by AMIRIOX** [comment]
好的 非常感谢您
