### ISSUE TITLE
建议停止对当事人的嘲讽

### ISSUE THREAD

**Issue by tinyvan** [TZG-official/Jvav#90]
谁不是从小孩子过来的呢
谁小时候没有装逼的想法呢

希望当事人能够健康成长，不受网络暴力的毒害

我之前的issue可能助长了该事的发展，在此深深忏悔

**Comment by TheZihanGu** [comment]
该事件当事人并未因此而产生消极心态，反而开始玩自己的梗，因此我并不认为该事件当事人受到了网络攻击的毒害。
同时，我们也并没有对该事件当事人进行嘲讽。因此我们并不会停止 Jvav 相关项目。
