### ISSUE TITLE
建议加一个小彩蛋。

### ISSUE THREAD

**Issue by nicccce** [TZG-official/Jvav#91]
如果在搜索框搜索java，会弹出一条java is rubbish，jvav is the best language in the world。（<script>java is rubbish，jvav is the best language in the world。</script>）
其他的也行，就是感觉一个搜索框太空了，就是搞笑玩的，没有任何恶意。

**Comment by nicccce** [comment]
不行，要不跳转到java.com？

**Comment by TheZihanGu** [comment]
> java is rubbish

你觉得我们要是加了这个，会产生多大的后果？

**Comment by nicccce** [comment]
换一个吧，太过分了

**Comment by TheZihanGu** [comment]
？

**Comment by TheZihanGu** [comment]
> 换一个吧，太过分了

？
