### ISSUE TITLE
建议在贡献者列表里加上我

### ISSUE THREAD

**Issue by xiaopangju** [TZG-official/Jvav#93]
如题，我曾经提供过帮助页面的一些脑洞
#59 
这算是一种贡献，所以请求加上我

**Comment by TheZihanGu** [comment]
👌 我这边贡献图片是直接按照 GitHub 贡献者做的，并没有考虑到 Issues 给出的意见。
明天把您加上。

**Comment by xiaopangju** [comment]
> 👌 我这边贡献图片是直接按照 GitHub 贡献者做的，并没有考虑到 Issues 给出的意见。
> 明天把您加上。

万分感谢！

**Comment by xiaopangju** [comment]
> 👌 我这边贡献图片是直接按照 GitHub 贡献者做的，并没有考虑到 Issues 给出的意见。
> 明天把您加上。

请问好了吗？半天过去了

**Comment by TheZihanGu** [comment]
> > 👌 我这边贡献图片是直接按照 GitHub 贡献者做的，并没有考虑到 Issues 给出的意见。
> > 明天把您加上。
> 
> 请问好了吗？半天过去了

那么着急干啥...有点事=-=

**Comment by xiaopangju** [comment]
> > > 👌 我这边贡献图片是直接按照 GitHub 贡献者做的，并没有考虑到 Issues 给出的意见。
> > > 明天把您加上。
> > 
> > 
> > 请问好了吗？半天过去了
> 
> 那么着急干啥...有点事=-=

不急，就随便问问~

**Comment by xiaopangju** [comment]
> > > ok_hand 我这边贡献图片是直接按照 GitHub 贡献者做的，并没有考虑到 Issues 给出的意见。
> > > 明天把您加上。
> > 
> > 
> > 请问好了吗？半天过去了
> 
> 那么着急干啥...有点事=-=

现在好了吗QAQ

**Comment by TheZihanGu** [comment]
> > > > ok_hand 我这边贡献图片是直接按照 GitHub 贡献者做的，并没有考虑到 Issues 给出的意见。
> > > > 明天把您加上。
> > > 
> > > 
> > > 请问好了吗？半天过去了
> > 
> > 
> > 那么着急干啥...有点事=-=
> 
> 现在好了吗QAQ

前几天就加上了...不过好像 GitHub 有缓存的样子🤔

**Comment by xiaopangju** [comment]
> > > > > ok_hand我这边贡献图片是直接按照GitHub贡献者做的，并没有考虑到Issues的意见。
> > > > > 明天把您加上。
> > > > 
> > > > 
> > > > 请问好了吗？半天过去了
> > > 
> > > 
> > > 那么着急干啥...有点事=-=
> > 
> > 
> > 现在好了吗QAQ
> 
> 前几天就加上了...不过好像GitHub有缓存的样子

啊？这缓存有多久啊。。。

**Comment by TheZihanGu** [comment]
> > > > > > ok_hand我这边贡献图片是直接按照GitHub贡献者做的，并没有考虑到Issues的意见。
> > > > > > 明天把您加上。
> > > > > 
> > > > > 
> > > > > 请问好了吗？半天过去了
> > > > 
> > > > 
> > > > 那么着急干啥...有点事=-=
> > > 
> > > 
> > > 现在好了吗QAQ
> > 
> > 
> > 前几天就加上了...不过好像GitHub有缓存的样子
> 
> 啊？这缓存有多久啊。。。

Jvav.top 上的应该没问题了，但是 GitHub README.md 就不知道了...
