### ISSUE TITLE
[Suggestion]Add these details

### ISSUE THREAD

**Issue by Alphaly2K** [TZG-official/Jvav#94]
## Jvav的弱类型
Jvav是一门超弱类型语言，您可以用var存储任何128位的数据，这将会导致您的程序运行速度极慢，稳定性极差，空间占用极高，但相应的，编码效率会提升，所以Jvav完全是适用于企业级马桶的语言。

**Comment by TheZihanGu** [comment]
👍

**Comment by TheZihanGu** [comment]
Commit: f177537
