### ISSUE TITLE
求张浩扬博士的原图照片

### ISSUE THREAD

**Issue by Jackwu945** [TZG-official/Jvav#98]
看完这个网站后，我计划做一个张浩扬博士的新型语言：Pythno，但是缺少张博士的照片1，求作者分享下。

**Comment by TheZihanGu** [comment]
![张浩洋博士.png](https://i.loli.net/2020/07/26/PiW81DCqbSg2KHu.png)

**Comment by TheZihanGu** [comment]
请在使用前获得肖像使用权。我们不对第三方使用负任何法律责任。
