### ISSUE TITLE
这个项目会不会引起 oracle 法务部的注意？

### ISSUE THREAD

**Issue by deadlineOvO** [TZG-official/Jvav#99]
就像标题描述的那样，不知道 oracle 会不会以这个项目侵权的理由为 github 送一个律师函

**Comment by xiaopangju** [comment]
我觉得他们没必要这么大费力气吧

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by cheny0y0** [comment]
应该会吧

**Comment by cheny0y0** [comment]
> 应该会吧

不会发律师函给GitHub的，因为网站不是GitHub写的，顶多发给 @TheZihanGu

**Comment by Dtue** [comment]
> > 应该会吧
> 
> 
> 
> 不会发律师函给GitHub的，因为网站不是GitHub写的，顶多发给 @TheZihanGu 

有请尊敬的罗翔老师来判一判

**Comment by cheny0y0** [comment]
> 网站样式应该都是ZihanGu自己写的，不算侵权吧。。

ZihanGu编写，GitHub提供服务，**呵呵**

**Comment by TheZihanGu** [comment]
> > 网站样式应该都是ZihanGu自己写的，不算侵权吧。。
> 
> ZihanGu编写，GitHub提供服务，**呵呵**

**呵呵**？这不是小学生经常用的词吗。别看则项目星多就酸啊，体面点。

**Comment by cheny0y0** [comment]
> > > 网站样式应该都是ZihanGu自己写的，不算侵权吧。。
> 
> > 
> 
> > ZihanGu编写，GitHub提供服务，**呵呵**
> 
> 
> 
> **呵呵**？这不是小学生经常用的词吗。别看则项目星多就酸啊，体面点。

`秀一秀 xiuyixiu xiù yí xiù`
